trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet test Web\Functions\WayPointSaverFunction.Tests\WayPointSaverFunction.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[SmartSkating]*
  displayName: 'Run WayPointSaver tests'

- bash: |
    curl -s https://codecov.io/bash > codecov
    chmod +x codecov
    ./codecov -f "Tests\Functions\LoginTests\coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload WayPointSaver tests results'

- script: dotnet build Web\Functions\WayPointSaverFunction\WayPointSaverFunction.csproj -c $(buildConfiguration) -v d
  displayName: 'Build WayPointSaver function'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Web\Functions\WayPointSaverFunction\netcoreapp3.0\'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: 'Web\Functions\WayPointSaverFunction\bin\Release\Function.zip'
    replaceExistingArchive: true
    verbose: true
  displayName: 'Archive functions'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: ''
    appType: 'functionApp'
    appName: 'smart-skating-dev'
    package: 'Web\Functions\WayPointSaverFunction\bin\Release\Function.zip'
    deploymentMethod: 'auto'
  displayName: 'Publish functions'
