trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: false

- script: dotnet restore SmartSkating.sln
  displayName: 'Restore nuget packages'

- script: dotnet test Shared/SmartSkating.Tests/SmartSkating.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=\"[SmartSkating]*,[SmartSkating.Dto]*\"
  displayName: 'Run Core tests'

- bash: |
    bash <(curl -s https://codecov.io/bash) -f "Shared/SmartSkating.Tests/coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload Core tests results'

- script: dotnet test Shared/SmartSkating.Dto.Tests/SmartSkating.Dto.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[SmartSkating.Dto]*
  displayName: 'Run Dto tests'

- bash: |
    bash <(curl -s https://codecov.io/bash) -f "Shared/SmartSkating.Dto.Tests/coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload Dto tests results'

- script: touch Tools/Misc/KeysProvider/appsettings.json
  displayName: 'Create settings file placeholder'

- script: dotnet test Tools/Misc/KeysProvider.Tests/KeysProvider.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  displayName: 'Run Tools.Keys Tests'

- bash: |
    bash <(curl -s https://codecov.io/bash) -f "Tools/Misc/KeysProvider.Tests/coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload Tools.Keys tests results'