#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sanet.SmartSkating.WearOs.Resource", IsApplication=true)]

namespace Sanet.SmartSkating.WearOs
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F010000
			public const int box_inset_layout_padding = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int inner_frame_layout_padding = 2130771969;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int best_lap = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int best_sector = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int confirmButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int confirmButtonSessions = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int distance = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int elapsed_time = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int info_label = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int laps = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int last_lap = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int last_sector = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int recyclerView = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int recyclerViewSessions = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int select_rink_button = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int startButton = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int stopButton = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int textView = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int track_name = 2130837520;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int activity_session = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int activity_sessions = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int activity_tracks = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int cell_track = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int hello_world = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
